name: Run Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: create .env.test
        run: echo "${{secrets.ENV_TEST_CONTENT}}" > .env.test
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
